####   PolynomialFeatures
Creates new features that are powers or combinations of your original features — allowing models (like linear regression) to fit non-linear relationships.

Expands input features into polynomial combinations.

Used to capture non-linear relationships in linear models.

For degree = 2:   [1,x,x2]

The first column (1) is the intercept term.
Now, model can learn curved shapes (e.g., parabolas) even with linear regression.


In [18]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

# Suppose you have one feature X
X = np.array([[2],
              [3],
              [4]])
# Create polynomial features up to degree 2
poly = PolynomialFeatures(degree=2)
X_poly = poly.fit_transform(X)

print("Original X:\n", X)
print("\nPolynomial Transformed X:\n", X_poly)
print("\nFeature Names:", poly.get_feature_names_out())

Original X:
 [[2]
 [3]
 [4]]

Polynomial Transformed X:
 [[ 1.  2.  4.]
 [ 1.  3.  9.]
 [ 1.  4. 16.]]

Feature Names: ['1' 'x0' 'x0^2']


In [19]:
# With two features:

X = np.array([[2, 3],
              [3, 5],
              [4, 6]])

poly = PolynomialFeatures(degree=2)
X_poly = poly.fit_transform(X)

print(X_poly)
print(poly.get_feature_names_out())

[[ 1.  2.  3.  4.  6.  9.]
 [ 1.  3.  5.  9. 15. 25.]
 [ 1.  4.  6. 16. 24. 36.]]
['1' 'x0' 'x1' 'x0^2' 'x0 x1' 'x1^2']
