In [2]:
# Data Cleaning a 4D Array with Masked Indexing¶
# You have a 4D array representing a batch of images, with shape (batch_size, height, width, channels). The data contains some noise and invalid values. Your goal is to clean it by clipping outliers and removing negative sensor errors.

# Your Task:

# Create a random 4D NumPy array named image_batch of shape (2, 10, 10, 3). Populate it with integers from -20 to 120.
# Create a boolean mask to identify all values that are "outliers" (less than 0 or greater than 100).
# Use the mask to clip the data: set all values greater than 100 to 100, and all values less than 0 to 0. (Hint: You can do this with two separate masks or one combined operation).
# Finally, create another mask to find all values that are exactly 0 and replace them with -1 to indicate they were corrected values.
# Print the array after clipping and after the final replacement.



import numpy as np

# Step 1: Create random 4D array (2 images, 10x10 pixels, 3 channels)
image_batch = np.random.randint(-20, 121, size=(2, 10, 10, 3))
print("Original image_batch:\n", image_batch)

# Step 2: Create boolean mask for outliers (<0 or >100)
outliers_mask = (image_batch < 0) | (image_batch > 100)

# Step 3: Clip outliers
# Set all >100 to 100
image_batch[image_batch > 100] = 100
# Set all <0 to 0
image_batch[image_batch < 0] = 0
print("\nAfter clipping:\n", image_batch)

# Step 4: Replace corrected values (0) with -1
corrected_mask = (image_batch == 0)
image_batch[corrected_mask] = -1
print("\nAfter replacing corrected values (0 -> -1):\n", image_batch)




# np.random.randint(-20, 121, size=(2, 10, 10, 3))
# → Generates values in range [-20, 120].

# Mask:

# (image_batch < 0) | (image_batch > 100)


# finds all invalid values.

# Clipping outliers:

# Values > 100 → 100

# Values < 0 → 0

# Mark corrected values:

# All 0s (from correction step) replaced with -1.

Original image_batch:
 [[[[112 105  46]
   [105  84  56]
   [ 81  -5  20]
   [ 33 106  90]
   [ 76  60  34]
   [ 37  39  41]
   [ 78  47  28]
   [ 40   4 -10]
   [ 73  79  89]
   [ 14 -12  14]]

  [[-16  26  84]
   [ -1 108  76]
   [-16  86  -5]
   [ 29  60 -10]
   [111   0  36]
   [ 79  84 100]
   [  9 110  75]
   [102  93  89]
   [ 27  -2  82]
   [ 32  63 104]]

  [[ 17 104  -2]
   [ 72  30  51]
   [ 28  55  41]
   [114  78  75]
   [ 50 106 -16]
   [ 22 102   0]
   [  2  43 105]
   [ 18  16  69]
   [ 18  58 118]
   [109  39   1]]

  [[119 -11  -2]
   [ 98 -19  63]
   [ 80 118  67]
   [ 59 105  76]
   [  5  18  40]
   [ 95 110  34]
   [ 20  34  10]
   [118  82  55]
   [ 97  46 102]
   [ 99  75  30]]

  [[ 99 111   5]
   [ 33  51   0]
   [115 -15  35]
   [ 47 -10  76]
   [108 113  99]
   [119   8  96]
   [ 36  52  67]
   [103  96  15]
   [ -8 113 -16]
   [ 33  76  65]]

  [[ 53  17  78]
   [ 56  -9  74]
   [ 71  93  73]
   [ 96  21 102]
   [ 58  45  76]
   [ 44  66  80]
   [ 99  -3  43