In [ ]:
# Power of number

# Write a function power that takes a number x and returns either its square, cube, or any power based on a keyword argument exp. If exp is not provided, use square (default = 2).

# Input: power(5)
# Output: 25

# Input: power(5, exp=3)
# Output: 125



def power(x, exp=2):
    """
    Return x raised to the power exp.
    Default exp = 2 (square).
    """
    return x ** exp

# Examples
print(power(5))            # 25 (square)
print(power(5, exp=3))     # 125 (cube)
print(power(2, exp=5))     # 32 (any power)



In [ ]:
# Keyword arguments statement print

# Write a function that introduces a person with name, age, and city. Use keyword arguments.

# Input: name="abc", city="xyz", age=123

# Output: My name is abc, I am 123 years old, and I live in xyz.



def introduce(name, age, city):
    """
    Introduce a person using keyword arguments.
    """
    print(f"My name is {name}, I am {age} years old, and I live in {city}.")

# Example usage
introduce(name="abc", city="xyz", age=123)



In [ ]:
 # Write a function normalize_list that takes a list of positive 
 # numbers and normalizes them so that all values are scaled down between 0 and 1, and the sum of 
 # the list is 1. Modify the list in-place and return nothing.

 # Input: [1, 4, 5]
 # Output: [0.1, 0.4, 0.5]

 # Input: [1, 3, 4, 8]
 # Output: [0.0625, 0.1875, 0.25, 0.5]



def normalize_list(nums):
    """
    Normalize a list of positive numbers so that:
    - Each element is scaled between 0 and 1
    - The sum of the list is 1
    Modifies the list in-place and returns nothing.
    """
    total = sum(nums)
    for i in range(len(nums)):
        nums[i] = nums[i] / total

# Example usage
data1 = [1, 4, 5]
normalize_list(data1)
print(data1)  # [0.1, 0.4, 0.5]

data2 = [1, 3, 4, 8]
normalize_list(data2)
print(data2)  # [0.0625, 0.1875, 0.25, 0.5]



In [ ]:
# The famous Collatz sequence can be generated for any starting positive integer as follows:

# Start with an arbitrary (positive) integer.

# If the number is even, divide by 2; if the number is odd, multiply by 3 and add 1.
# Repeat the procedure with the new number.
# It appears that for all starting values there is a cycle of 4, 2, 1 at 
# which the procedure loops. You should stop when the value goes to 1.
# Write a program that prints out the Collatz sequence given a starting value.

def collatz_sequence(n):
    """
    Print the Collatz sequence starting from n until reaching 1.
    """
    if n <= 0:
        print("Please provide a positive integer.")
        return

    sequence = [n]
    while n != 1:
        if n % 2 == 0:
            n = n // 2
        else:
            n = 3 * n + 1
        sequence.append(n)

    print("Collatz sequence:", sequence)

# Example usage
collatz_sequence(6)



In [ ]:
# Write a function that is given a starting value (a positive integer), and
#    returns a list with the Collatz sequence.


def collatz_sequence(n):
    """
    Generate the Collatz sequence starting from a positive integer n.
    Returns the sequence as a list.
    """
    if n <= 0:
        raise ValueError("Starting value must be a positive integer.")

    sequence = [n]
    while n != 1:
        if n % 2 == 0:
            n = n // 2
        else:
            n = 3 * n + 1
        sequence.append(n)

    return sequence

# Example usage
print(collatz_sequence(6))   # [6, 3, 10, 5, 16, 8, 4, 2, 1]
print(collatz_sequence(11))  # [11, 34, 17, 52, 26, 13, 40, 20, 10, 5, 16, 8, 4, 2, 1]


In [ ]:
# Write a function that is given a single argument of an integer (with arbitrary number of digits),
# return the number of digits the number has.

def count_digits(n: int) -> int:
    """
    Return the number of digits in an integer.
    Handles positive and negative integers.
    """
    return len(str(abs(n)))

# Example usage
print(count_digits(12345))   # 5
print(count_digits(-98765))  # 5
print(count_digits(0))       # 1


In [ ]:
# Write a function called difference that is given two lists, 
# you should return a list of any elements that is not common to both the lists.

def difference(list1, list2):
    """
    Return a list of elements that are not common to both lists.
    """
    return list(set(list1).symmetric_difference(set(list2)))

# Example usage
print(difference([1, 2, 3, 4], [3, 4, 5, 6]))  
# [1, 2, 5, 6]




In [10]:
# Replace All Negative Numbers with Zero
# Given a list of integers, replace all negative numbers with 0

# Input: [-3, 5, -1, 7]  
# Output: [0, 5, 0, 7]


def replace_negatives(nums):
    """
    Replace all negative numbers in a list with 0.
    Modifies the list in-place and also returns it.
    """
    for i in range(len(nums)):
        if nums[i] < 0:
            nums[i] = 0
    return nums

# Example usage
print(replace_negatives([-3, 5, -1, 7]))  # [0, 5, 0, 7]


[0, 5, 0, 7]


In [20]:

# list comprehensions in Python are a concise way to create lists.
# Squares of numbers 0–9

squares = [x**2 for x in range(10)]
print(squares)  # [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


# Even numbers from 0–20

evens = [x for x in range(21) if x % 2 == 0]
print(evens)  # [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


# Convert list of strings to uppercase


words = ["apple", "banana", "cherry"]
uppercased = [w.upper() for w in words]
print(uppercased)  # ['APPLE', 'BANANA', 'CHERRY']

# Replace negatives with 0

nums = [-3, 5, -1, 7]
normalized = [x if x >= 0 else 0 for x in nums]
print(normalized)  # [0, 5, 0, 7]


# Extract first letters

names = ["Alice", "Bob", "Charlie"]
first_letters = [name[0] for name in names]
print(first_letters)  # ['A', 'B', 'C']


#Flatten a 2D list

matrix = [[1, 2, 3], [4, 5], [6, 7]]
flat = [num for row in matrix for num in row]
print(flat)  # [1, 2, 3, 4, 5, 6, 7]


# Create multiplication table

table = [i*j for i in range(1, 4) for j in range(1, 4)]
print(table)  
# [1, 2, 3, 2, 4, 6, 3, 6, 9]


# Create a dictionary of squares

squares = {x: x**2 for x in range(5)}
print(squares)  # {0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

# Swap keys and values

my_dict = {"a": 1, "b": 2, "c": 3}
swapped = {v: k for k, v in my_dict.items()}
print(swapped)  # {1: 'a', 2: 'b', 3: 'c'}

# Filter dictionary items

grades = {"Alice": 85, "Bob": 60, "Charlie": 95}
passed = {name: grade for name, grade in grades.items() if grade >= 70}
print(passed)  # {'Alice': 85, 'Charlie': 95}


# Unique squares

nums = [1, 2, 2, 3, 4, 4]
squares_set = {x**2 for x in nums}
print(squares_set)  # {16, 1, 4, 9}


# First letters of words

words = ["apple", "banana", "cherry", "apricot"]
letters = {word[0] for word in words}
print(letters)  # {'a', 'b', 'c'}


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
['APPLE', 'BANANA', 'CHERRY']
[0, 5, 0, 7]
['A', 'B', 'C']
[1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 2, 4, 6, 3, 6, 9]
{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}
{1: 'a', 2: 'b', 3: 'c'}
{'Alice': 85, 'Charlie': 95}
{16, 1, 4, 9}
{'c', 'b', 'a'}


In [21]:


# Passing a function to another function

def apply_func(f, values):
    return [f(x) for x in values]

def square(x):
    return x ** 2

def cube(x):
    return x ** 3

nums = [1, 2, 3, 4]
print(apply_func(square, nums))  # [1, 4, 9, 16]
print(apply_func(cube, nums))    # [1, 8, 27, 64]


[1, 4, 9, 16]
[1, 8, 27, 64]


In [22]:
# Returning a function (closures)

def power_func(exp):
    def inner(x):
        return x ** exp
    return inner

square = power_func(2)
cube = power_func(3)

print(square(5))  # 25
print(cube(5))    # 125



25
125


In [24]:
# Using built-in higher-order functions


nums = [1, 2, 3, 4, 5]

# Using map with a lambda function
squared = list(map(lambda x: x**2, nums))
print(squared)  # [1, 4, 9, 16, 25]

# Using filter to keep even numbers
evens = list(filter(lambda x: x % 2 == 0, nums))
print(evens)  # [2, 4]



[1, 4, 9, 16, 25]
[2, 4]


In [25]:
# Flattening Arrays

import numpy as np

# Example: 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original 2D array:\n", arr)

# Flatten using ravel()
flat1 = arr.ravel()
print("Flattened with ravel:", flat1)

# Flatten using flatten()
flat2 = arr.flatten()
print("Flattened with flatten:", flat2)

# Flatten using reshape()
flat3 = arr.reshape(-1)
print("Flattened with reshape:", flat3)


Original 2D array:
 [[1 2 3]
 [4 5 6]]
Flattened with ravel: [1 2 3 4 5 6]
Flattened with flatten: [1 2 3 4 5 6]
Flattened with reshape: [1 2 3 4 5 6]


In [26]:
# Multidimensional Arrays

# NumPy arrays can have any number of dimensions:


# 1D Array
a1 = np.array([1, 2, 3])
print("1D:", a1)

# 2D Array (matrix)
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D (matrix):\n", a2)

# 3D Array (tensor)
a3 = np.array([[[1, 2], [3, 4]],
               [[5, 6], [7, 8]]])
print("3D:\n", a3)

print("Shape of a3:", a3.shape)  # (2, 2, 2)


1D: [1 2 3]
2D (matrix):
 [[1 2 3]
 [4 5 6]]
3D:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape of a3: (2, 2, 2)


In [27]:
# Matrix Operations

# In NumPy, matrices are just 2D arrays. You can do matrix math easily:


# Define two matrices
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# Elementwise operations
print("A + B:\n", A + B)
print("A * B (elementwise):\n", A * B)

# Matrix multiplication
print("A @ B (matrix product):\n", A @ B)     # Python 3.5+
print("np.dot(A, B):\n", np.dot(A, B))

# Transpose
print("Transpose of A:\n", A.T)

# Inverse
from numpy.linalg import inv
print("Inverse of A:\n", inv(A))

# Determinant
from numpy.linalg import det
print("Determinant of A:", det(A))



A + B:
 [[ 6  8]
 [10 12]]
A * B (elementwise):
 [[ 5 12]
 [21 32]]
A @ B (matrix product):
 [[19 22]
 [43 50]]
np.dot(A, B):
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant of A: -2.0000000000000004


In [28]:
# Flattening Higher-Dimensional Arrays

tensor = np.arange(24).reshape(2, 3, 4)
print("3D Array:\n", tensor)
print("Flattened:", tensor.flatten())


3D Array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
